import Head from 'next/head'
import Layout from "../components/layout";

export default function Home() {
  return (
    <Layout>
      <Head>
        <title>코딩 포트폴리오</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <h1>홈입니다</h1>
    </Layout>
  )
}
