import React from 'react';
import Layout from "../components/Layout";
import Head from "next/head";

function Projects(props) {
    return (
        <Layout>
            <Head>
                <title>코딩 포트폴리오</title>
                <meta name="description" content="Generated by create next app"/>
                <link rel="icon" href="/favicon.ico"/>
            </Head>
            <h1>프로젝트</h1>
        </Layout>
    );
}

export default Projects;