import React from 'react';
import Layout from "../components/Layout";
import Head from "next/head";
import {DATABASE_ID, TOKEN} from "../config";

function Projects({projects}) {

    console.log(projects)

    return (
        <Layout>
            <Head>
                <title>코딩 포트폴리오</title>
                <meta name="description" content="Generated by create next app"/>
                <link rel="icon" href="/favicon.ico"/>
            </Head>
            <h1>총 프로젝트 : {projects.results.length}</h1>
            {
                projects.results.map((project, idx) => {
                    return (
                        <h1 key={idx}>{project.properties.이름.title[0]?.plain_text}</h1>
                    )
                })
            }
        </Layout>
    );
}

export default Projects;

// 빌드 타임에 호출
export async function getStaticProps() {
    const options = {
        method: 'POST',
        headers: {
            Accept: 'application/json',
            'Notion-Version': '2022-02-22',
            'Content-Type': 'application/json',
            Authorization: `Bearer ${TOKEN}`
        },
        body: JSON.stringify({
            sorts: [
                {
                    "property": "이름",
                    "direction": "ascending"
                }
            ],
            page_size: 100})
    };

    const res = await fetch(`https://api.notion.com/v1/databases/${DATABASE_ID}/query`, options)
    const projects = await res.json()

    return {
        props: {projects}
    }
}